---
apiVersion: "networking.k8s.io/v1"
kind: "Ingress"
metadata:
  name: "default"
  namespace: "default"
spec:
  rules:
  - http:
      paths:
      - path: "/*"
        backend:
          service:
            name: "hello-kubernetes-service"
            port:
              number: 8080
        pathType: "ImplementationSpecific"
status:
  loadBalancer: {}
