---
apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetes-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: hello-kubernetes
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
